import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { createReadStream, existsSync } from 'node:fs';
import { createServer } from 'node:http';
import { extname, join, normalize } from 'node:path';
import pg from 'pg';

const { Pool } = pg; const root = process.cwd(); const port = Number(process.env.PORT || 4173); const secret = process.env.SESSION_SECRET;
if (!process.env.DATABASE_URL || !secret) throw new Error('DATABASE_URL and SESSION_SECRET are required');
const db = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_URL.includes('railway') ? { rejectUnauthorized: false } : undefined });
const json = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json', 'access-control-allow-origin': process.env.CORS_ORIGIN || '*', 'access-control-allow-headers': 'content-type, authorization' }); res.end(JSON.stringify(body)); };
const read = req => new Promise((resolve, reject) => { let body=''; req.on('data', x => body += x); req.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error('Invalid JSON')); } }); });
const hash = password => { const salt=randomBytes(16).toString('hex'); return `${salt}:${scryptSync(password,salt,64).toString('hex')}`; };
const check = (password, stored) => { const [salt, value]=stored.split(':'); return timingSafeEqual(Buffer.from(value,'hex'), scryptSync(password,salt,64)); };
const token = user => { const data=Buffer.from(JSON.stringify({ sub:user.id, email:user.email, exp:Date.now()+86400000})).toString('base64url'); return `${data}.${createHmac('sha256',secret).update(data).digest('base64url')}`; };
function user(req) { const raw=req.headers.authorization?.replace('Bearer ',''); if(!raw) throw new Error('Authentication required'); const [data,signature]=raw.split('.'); if(!timingSafeEqual(Buffer.from(signature),Buffer.from(createHmac('sha256',secret).update(data).digest('base64url')))) throw new Error('Invalid token'); const claims=JSON.parse(Buffer.from(data,'base64url')); if(claims.exp<Date.now()) throw new Error('Session expired'); return claims; }
async function api(req,res,url) { if(req.method==='OPTIONS') return json(res,204,{}); if(url.pathname==='/api/health') { await db.query('select 1'); return json(res,200,{status:'ok'}); } if(req.method==='POST'&&url.pathname==='/api/auth/register'){ const b=await read(req); if(!b.email||!b.password||b.password.length<12)return json(res,400,{error:'Email and 12-character password required'}); const result=await db.query('insert into users(email,password_hash,display_name) values($1,$2,$3) returning id,email,display_name',[b.email.toLowerCase(),hash(b.password),b.displayName||null]); return json(res,201,{user:result.rows[0],token:token(result.rows[0])}); } if(req.method==='POST'&&url.pathname==='/api/auth/login'){const b=await read(req);const result=await db.query('select id,email,display_name,password_hash from users where email=$1',[b.email?.toLowerCase()]);if(!result.rowCount||!check(b.password,result.rows[0].password_hash))return json(res,401,{error:'Invalid email or password'});const {password_hash,...account}=result.rows[0];return json(res,200,{user:account,token:token(account)});} const account=user(req); if(req.method==='GET'&&url.pathname==='/api/auth/me')return json(res,200,account); if(req.method==='GET'&&url.pathname==='/api/behaviors'){const rows=await db.query('select b.*,v.specification from behaviors b join behavior_versions v on v.behavior_id=b.id and v.version=b.current_version where b.user_id=$1 order by b.updated_at desc',[account.sub]);return json(res,200,rows.rows);} if(req.method==='POST'&&url.pathname==='/api/behaviors'){const b=await read(req);if(!b.intent)return json(res,400,{error:'intent is required'});const spec={goal:b.intent,triggers:b.triggers||[{type:'manual.start'}],conditions:b.conditions||[],actions:b.actions||[],safeguards:[{rule:'never_unlock_doors'}],termination:b.termination||[{type:'timeout',afterMinutes:60}]};const client=await db.connect();try{await client.query('begin');const row=(await client.query('insert into behaviors(user_id,name,goal,status) values($1,$2,$3,$4) returning *',[account.sub,b.name||'Custom Environment',b.intent,'draft'])).rows[0];await client.query('insert into behavior_versions(behavior_id,version,specification,created_by) values($1,1,$2,$3)',[row.id,spec,account.sub]);await client.query('commit');return json(res,201,{...row,...spec,behaviorId:row.id,version:1});}catch(e){await client.query('rollback');throw e;}finally{client.release();}} if(req.method==='POST'&&url.pathname.match(/^\/api\/behaviors\/[^/]+\/deploy$/)){const id=url.pathname.split('/')[3];const result=await db.query("update behaviors set status='deployed',updated_at=now() where id=$1 and user_id=$2 returning *",[id,account.sub]);if(!result.rowCount)return json(res,404,{error:'Behavior not found'});return json(res,200,result.rows[0]);} return json(res,404,{error:'Not found'}); }
createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);try{if(url.pathname.startsWith('/api/'))return await api(req,res,url);const file=join(root,url.pathname==='/'?'index.html':normalize(url.pathname).replace(/^[/\\]+/,''));if(!file.startsWith(root)||!existsSync(file)){res.writeHead(404);return res.end();}res.writeHead(200,{'content-type':{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[extname(file)]||'application/octet-stream'});createReadStream(file).pipe(res);}catch(error){json(res,error.message.includes('Authentication')||error.message.includes('token')||error.message.includes('Session')?401:400,{error:error.message});}}).listen(port,()=>console.log(`Nexus production API on :${port}`));
