import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { validateBehaviorSpecification } from '../behavior-schema.mjs';

function minutesNow(date = new Date()) { return date.getHours() * 60 + date.getMinutes(); }
function timeMatches(condition, date = new Date()) { const parse = value => { const [hours, minutes] = value.split(':').map(Number); return hours * 60 + minutes; }; const now = minutesNow(date); const start = parse(condition.start); const end = parse(condition.end); return start <= end ? now >= start && now <= end : now >= start || now <= end; }

export class LocalBehaviorRuntime {
  constructor(path, inventory, execute) { this.path = path; this.inventory = inventory; this.execute = execute; this.behaviors = {}; if (existsSync(path)) this.behaviors = JSON.parse(readFileSync(path, 'utf8')).behaviors || {}; }
  save() { writeFileSync(this.path, JSON.stringify({ behaviors: this.behaviors }, null, 2), { mode: 0o600 }); }
  list() { return Object.values(this.behaviors); }
  deploy(behavior) { if (!String(behavior.behaviorId || '').trim()) throw new Error('behaviorId is required'); const devices = this.inventory.list().map(device => ({ ...device, deviceId: device.discoveryId, capabilities: device.capabilities || supportedCapabilities(device.adapter) })); const validation = validateBehaviorSpecification(behavior, devices); if (!validation.valid) throw new Error(`Behavior is not grounded locally: ${validation.issues.join('; ')}`); const stored = { ...behavior, status: 'deployed', deployedAt: new Date().toISOString(), lastRun: null }; this.behaviors[behavior.behaviorId] = stored; this.save(); return stored; }
  pause(id) { if (!this.behaviors[id]) throw new Error('Behavior not found'); this.behaviors[id].status = 'paused'; this.save(); return this.behaviors[id]; }
  conditionsMatch(conditions, event) { return (conditions || []).every(condition => condition.type === 'time.between' ? timeMatches(condition) : condition.type === 'event.value' ? event.value === condition.value : true); }
  async dispatch(event) { const runs = []; for (const behavior of this.list()) { if (behavior.status !== 'deployed') continue; const triggered = behavior.triggers.some(trigger => trigger.type === event.type && (!trigger.deviceId || trigger.deviceId === event.deviceId)); if (!triggered || !this.conditionsMatch(behavior.conditions, event)) continue; const results = []; for (const [index, action] of behavior.actions.entries()) results.push(await this.runAction(behavior, action, index)); behavior.lastRun = { at: new Date().toISOString(), event, results }; this.save(); runs.push({ behaviorId: behavior.behaviorId, results }); } return runs; }
  async runAction(behavior, action, index) { const device = this.inventory.list().find(item => item.discoveryId === action.deviceId); try { if (!device || device.status === 'offline') throw new Error('Primary device is offline'); return { action, result: await this.execute(device, action, this.inventory), fallback: false }; } catch (error) { const fallback = (behavior.fallbacks || []).find(item => item.forAction === index && ['offline', 'timeout', 'unconfirmed'].includes(item.when)); if (!fallback) return { action, error: error.message, fallback: false }; const alternate = this.inventory.list().find(item => item.discoveryId === fallback.action.deviceId); if (!alternate) return { action, error: `${error.message}; fallback device unavailable`, fallback: false }; try { return { action: fallback.action, result: await this.execute(alternate, fallback.action, this.inventory), fallback: true, primaryError: error.message }; } catch (fallbackError) { return { action: fallback.action, error: fallbackError.message, fallback: true, primaryError: error.message }; } }
  }
}

function supportedCapabilities(adapter) { if (adapter === 'hue_bridge') return ['light.turn_on', 'light.turn_off', 'light.set_brightness', 'light.set_temperature']; if (adapter === 'shelly') return ['light.turn_on', 'light.turn_off']; return []; }
