import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { validateBehaviorSpecification } from '../behavior-schema.mjs';

const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const parseTime = value => { const [hours, minutes] = String(value).split(':').map(Number); return hours * 60 + minutes; };
function timeMatches(condition, date = new Date()) { const now = date.getHours() * 60 + date.getMinutes(); const start = parseTime(condition.start); const end = parseTime(condition.end); return start <= end ? now >= start && now <= end : now >= start || now <= end; }
function supportedCapabilities(adapter) { if (adapter === 'hue_bridge') return ['light.turn_on', 'light.turn_off', 'light.set_brightness', 'light.set_temperature']; if (adapter === 'shelly') return ['light.turn_on', 'light.turn_off']; return []; }

export class LocalBehaviorRuntime {
  constructor(path, inventory, execute) { this.path = path; this.inventory = inventory; this.execute = execute; this.behaviors = {}; this.context = {}; this.overrides = {}; this.timer = null; if (existsSync(path)) { const saved = JSON.parse(readFileSync(path, 'utf8')); this.behaviors = saved.behaviors || {}; this.context = saved.context || {}; this.overrides = saved.overrides || {}; } }
  save() { writeFileSync(this.path, JSON.stringify({ behaviors: this.behaviors, context: this.context, overrides: this.overrides }, null, 2), { mode: 0o600 }); }
  list() { return Object.values(this.behaviors); }
  start() { if (this.timer) return; this.timer = setInterval(() => this.dispatch({ type: 'schedule.tick', occurredAt: new Date().toISOString() }).catch(error => console.error(`Nexus schedule: ${error.message}`)), 60_000); this.timer.unref(); }
  deploy(behavior) { if (!String(behavior.behaviorId || '').trim()) throw new Error('behaviorId is required'); const devices = this.inventory.list().map(device => ({ ...device, deviceId: device.discoveryId, capabilities: device.capabilities || supportedCapabilities(device.adapter) })); const validation = validateBehaviorSpecification(behavior, devices); if (!validation.valid) throw new Error(`Behavior is not grounded locally: ${validation.issues.join('; ')}`); const stored = { ...behavior, status: 'deployed', deployedAt: new Date().toISOString(), lastRun: null }; this.behaviors[behavior.behaviorId] = stored; this.save(); return stored; }
  pause(id) { if (!this.behaviors[id]) throw new Error('Behavior not found'); this.behaviors[id].status = 'paused'; this.save(); return this.behaviors[id]; }
  observe(event) { if (event.type === 'device.manual_override' && event.deviceId) this.overrides[event.deviceId] = Date.now() + Math.max(1, Math.min(Number(event.holdMinutes || 30), 1440)) * 60_000; if (event.contextType) this.context[event.contextType] = { value: event.value, observedAt: event.occurredAt || new Date().toISOString(), expiresAt: event.expiresAt || null }; this.save(); }
  conditionsMatch(conditions, event) { return (conditions || []).every(condition => { if (condition.type === 'time.between') return timeMatches(condition); if (condition.type === 'event.value') return event.value === condition.value; if (condition.type === 'context.equals') { const fact = this.context[condition.contextType]; return fact && (!fact.expiresAt || new Date(fact.expiresAt) > new Date()) && fact.value === condition.value; } return false; }); }
  triggerMatches(trigger, event) { if (trigger.type === 'schedule') return event.type === 'schedule.tick' && (!trigger.at || parseTime(trigger.at) === new Date().getHours() * 60 + new Date().getMinutes()); return trigger.type === event.type && (!trigger.deviceId || trigger.deviceId === event.deviceId); }
  async dispatch(event) { this.observe(event); const runs = []; const candidates = this.list().filter(behavior => behavior.status === 'deployed' && behavior.triggers.some(trigger => this.triggerMatches(trigger, event)) && this.conditionsMatch(behavior.conditions, event)).sort((a, b) => Number(b.priority || 0) - Number(a.priority || 0)); for (const behavior of candidates) { const results = []; for (const [index, action] of behavior.actions.entries()) { if (action.delaySeconds) await wait(Math.min(Number(action.delaySeconds), 3600) * 1000); results.push(await this.runAction(behavior, action, index)); } behavior.lastRun = { at: new Date().toISOString(), event, results }; this.save(); runs.push({ behaviorId: behavior.behaviorId, results }); } return runs; }
  async executeWithRetry(device, action) { let error; for (let attempt = 1; attempt <= 3; attempt += 1) { try { const result = await this.execute(device, action, this.inventory); if (this.inventory.markStatus) this.inventory.markStatus(device.discoveryId, 'online'); return { result, attempts: attempt }; } catch (caught) { error = caught; if (attempt < 3) await wait(150 * 2 ** (attempt - 1)); } } if (this.inventory.markStatus) this.inventory.markStatus(device.discoveryId, 'offline'); throw error; }
  async runAction(behavior, action, index) { if ((this.overrides[action.deviceId] || 0) > Date.now()) return { action, skipped: true, reason: 'manual_override' }; const device = this.inventory.list().find(item => item.discoveryId === action.deviceId); try { if (!device || device.status === 'offline') throw new Error('Primary device is offline'); return { action, ...(await this.executeWithRetry(device, action)), fallback: false }; } catch (error) { const failure = /offline/i.test(error.message) ? 'offline' : /abort|timeout/i.test(error.message) ? 'timeout' : 'unconfirmed'; const fallback = (behavior.fallbacks || []).find(item => item.forAction === index && item.when === failure); if (!fallback) return { action, error: error.message, failure, fallback: false }; const alternate = this.inventory.list().find(item => item.discoveryId === fallback.action.deviceId); if (!alternate || (this.overrides[alternate.discoveryId] || 0) > Date.now()) return { action, error: `${error.message}; fallback device unavailable`, failure, fallback: false }; try { return { action: fallback.action, ...(await this.executeWithRetry(alternate, fallback.action)), fallback: true, primaryError: error.message }; } catch (fallbackError) { return { action: fallback.action, error: fallbackError.message, fallback: true, primaryError: error.message }; } }
  }
}
