CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, password_hash text NOT NULL, display_name text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organization_members (organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('owner','admin','member')), PRIMARY KEY (organization_id,user_id));
CREATE TABLE provider_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, provider text NOT NULL, access_token_encrypted text NOT NULL, refresh_token_encrypted text, expires_at timestamptz, scopes jsonb NOT NULL DEFAULT '[]', status text NOT NULL DEFAULT 'connected', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,provider));
CREATE TABLE devices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, provider_connection_id uuid REFERENCES provider_connections(id) ON DELETE CASCADE, provider_device_id text NOT NULL, name text NOT NULL, room text, type text NOT NULL, online boolean NOT NULL DEFAULT true, reported_state jsonb NOT NULL DEFAULT '{}', observed_at timestamptz, UNIQUE(provider_connection_id,provider_device_id));
CREATE TABLE device_capabilities (device_id uuid REFERENCES devices(id) ON DELETE CASCADE, capability text NOT NULL, constraints jsonb NOT NULL DEFAULT '{}', PRIMARY KEY(device_id,capability));
CREATE TABLE context_facts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, type text NOT NULL, value jsonb NOT NULL, source text NOT NULL, confidence numeric(3,2), observed_at timestamptz NOT NULL, expires_at timestamptz, permission_level text NOT NULL DEFAULT 'standard');
CREATE TABLE behaviors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, goal text NOT NULL, status text NOT NULL CHECK(status IN ('draft','deployed','paused','archived')), current_version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE behavior_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), behavior_id uuid REFERENCES behaviors(id) ON DELETE CASCADE, version integer NOT NULL, specification jsonb NOT NULL, simulation jsonb, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(behavior_id,version));
CREATE TABLE approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, behavior_version_id uuid REFERENCES behavior_versions(id) ON DELETE CASCADE, action_hash text NOT NULL, status text NOT NULL CHECK(status IN ('approved','executed','revoked','expired')), approved_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, executed_at timestamptz);
CREATE TABLE executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), approval_id uuid REFERENCES approvals(id), behavior_id uuid REFERENCES behaviors(id), idempotency_key text UNIQUE NOT NULL, status text NOT NULL, request jsonb NOT NULL, receipt jsonb, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), behavior_id uuid REFERENCES behaviors(id), type text NOT NULL, detail jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE behavior_packages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), publisher_id uuid REFERENCES users(id), slug text UNIQUE NOT NULL, name text NOT NULL, description text, required_capabilities jsonb NOT NULL, specification jsonb NOT NULL, visibility text NOT NULL CHECK(visibility IN ('private','unlisted','public')), version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE package_installations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id uuid REFERENCES behavior_packages(id), user_id uuid REFERENCES users(id), capability_mapping jsonb NOT NULL, installed_behavior_id uuid REFERENCES behaviors(id), installed_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX context_facts_active ON context_facts(user_id,type,expires_at);
CREATE INDEX audit_events_user_time ON audit_events(user_id,occurred_at DESC);
