const $ = (selector) => document.querySelector(selector);
let sessionToken = localStorage.getItem('nexus_session');
const api = async (path, options = {}) => {
  const response = await fetch(`/api${path}`, { headers: { 'content-type': 'application/json', ...(sessionToken ? { authorization: `Bearer ${sessionToken}` } : {}), ...(options.headers || {}) }, ...options });
  const text = await response.text(); const data = text ? JSON.parse(text) : {};
  if (!response.ok) throw new Error(data.error || 'Nexus could not complete that request');
  return data;
};

let devices = [];
let behaviors = [];
let providers = [];
let agents = [];
let account = null;
let candidate = null;
const toast = (message) => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 3200); };
const risk = (capability) => /thermostat|lock|alarm|garage|camera/.test(capability) ? 'medium' : 'low';
const actionText = (action) => `${action.capability} · ${Object.entries(action.parameters || {}).map(([key, value]) => `${key}: ${value}`).join(', ') || 'default'}`;

function behaviorCard(behavior, wide = false) {
  const status = behavior.status === 'deployed' ? '● Deployed' : '◌ Draft';
  const chips = behavior.actions.slice(0, 2).map(action => `<span>${actionText(action)}</span>`).join('') || '<span>No compatible actions found</span>';
  return `<article class="behavior-card ${wide ? 'wide' : ''}"><div class="card-top"><i class="card-icon">✦</i><span class="status ${behavior.status}">${status}</span></div><h3>${behavior.name}</h3><p>${behavior.goal}</p><div class="chips">${chips}</div><div class="card-footer"><small>Version ${behavior.version} · ${behavior.actions.length} actions</small><button class="outline review" data-id="${behavior.behaviorId}">Review</button></div></article>`;
}
function renderBehaviors() { $('#behavior-count').textContent = behaviors.length; $('#behavior-cards').innerHTML = behaviors.slice(0, 3).map(behavior => behaviorCard(behavior)).join('') || '<div class="empty">Describe your first environment behavior.</div>'; $('#behavior-library').innerHTML = behaviors.map(behavior => behaviorCard(behavior, true)).join('') || '<div class="empty">No behaviors yet.</div>'; }
function renderDevices() { $('#device-list').innerHTML = devices.map(device => `<article class="device"><div><i>◌</i><span><p class="label">${device.room.toUpperCase()} · ${device.type.toUpperCase()}</p><h3>${device.name}</h3></span><b>${device.online ? 'Online' : 'Offline'}</b></div><section>${device.capabilities.map(capability => `<span>${capability}</span>`).join('')}</section></article>`).join('') || '<div class="empty">Connect an ecosystem, then synchronize its devices to build your capability graph.</div>'; }
function renderProviders() {
  const connected = providers.filter(provider => provider.connected).length;
  const available = providers.filter(provider => provider.availability === 'available').length;
  $('#provider-summary').textContent = `${connected} connected · ${available} integrations ready`;
  $('#provider-list').innerHTML = providers.map(provider => {
    const state = provider.connected ? 'Connected' : provider.availability === 'planned' ? 'Planned' : provider.configured ? 'Ready to connect' : 'Needs server setup';
    const button = provider.connected ? `<button class="outline sync-provider" data-provider="${provider.id}">Sync devices</button>` : `<button class="${provider.availability === 'planned' ? 'outline' : 'primary'} connect-provider" data-provider="${provider.id}" ${provider.availability === 'planned' ? 'disabled' : ''}>${provider.availability === 'planned' ? 'Coming soon' : `Connect ${provider.name}`}</button>`;
    return `<article class="provider-card"><div class="provider-top"><div><p class="label">${provider.availability === 'planned' ? 'PLANNED ECOSYSTEM' : 'USER-AUTHORIZED ECOSYSTEM'}</p><h3>${provider.name}</h3></div><span class="provider-state ${provider.connected ? 'connected' : ''}">${state}</span></div><p>${provider.consent}</p><div class="provider-footer">${button}</div></article>`;
  }).join('');
}
function renderAgents() { $('#agent-list').innerHTML = agents.map(agent => `<article class="provider-card"><div class="provider-top"><div><p class="label">LOCAL NEXUS ENGINE</p><h3>${agent.name}</h3></div><span class="provider-state ${agent.status === 'online' ? 'connected' : ''}">${agent.status}</span></div><p>${agent.deviceCount || 0} synchronized devices · ${agent.lastSeenAt ? `Last seen ${new Date(agent.lastSeenAt).toLocaleString()}` : 'Waiting for first connection'}</p><div class="provider-footer"><button class="outline revoke-agent" data-agent="${agent.id}">Revoke agent</button></div></article>`).join('') || '<div class="empty">Add a home agent to discover and run devices locally.</div>'; }
function renderActivity(events) { const markup = events.map(event => `<div class="activity"><i class="activity-icon system">⌁</i><div><strong>${event.type}</strong><p>${JSON.stringify(event.detail)}</p></div><time>${new Date(event.at).toLocaleTimeString()}</time></div>`).join('') || '<div class="empty">No runtime activity yet.</div>'; $('#activity-list').innerHTML = markup.slice(0, 2000); $('#full-activity-list').innerHTML = markup; }
function renderSpaceStats() { const rooms = new Set(devices.map(device => device.room)).size; const capabilityCount = new Set(devices.flatMap(device => device.capabilities)).size; $('#device-count').textContent = devices.length; $('#room-count').textContent = rooms; $('#capability-count').textContent = capabilityCount; $('#home-device-summary').textContent = `${devices.filter(device => device.online).length} connected devices online`; }
async function refresh() { [devices, behaviors, providers, agents] = await Promise.all([api('/devices'), api('/behaviors'), api('/providers'), api('/agents')]); renderDevices(); renderBehaviors(); renderProviders(); renderAgents(); renderSpaceStats(); renderActivity(await api('/audit-events')); }
function planAction(action) { const device = devices.find(item => item.deviceId === action.deviceId); return `<div class="plan-action"><i>${risk(action.capability) === 'low' ? '✓' : '!'}</i><span><strong>${device?.name || action.deviceId}</strong><small>${actionText(action)}</small></span><b class="risk ${risk(action.capability)}">${risk(action.capability)} risk</b></div>`; }
async function review(behavior) { candidate = behavior; const simulation = await api(`/behaviors/${behavior.behaviorId}/simulate`, { method: 'POST' }); $('#plan-title').textContent = behavior.name; $('#plan-summary').textContent = behavior.goal; $('#plan-context').innerHTML = `<strong>Generated behavior</strong><span>${behavior.triggers.length} trigger(s)</span><span>${behavior.conditions.length} condition(s)</span><span>${behavior.termination[0]?.afterMinutes || 0} minute timeout</span>`; $('#plan-actions').innerHTML = behavior.actions.map(planAction).join('') || '<p class="muted">No compatible devices are currently available. Connect and sync an ecosystem first.</p>'; $('#plan-policy').innerHTML = simulation.simulation.blocked.length ? `<div class="policy caution"><strong>Cannot deploy yet</strong><span>${simulation.simulation.blocked.length} action(s) require changes or explicit handling.</span></div>` : `<div class="policy good"><strong>Simulation passed</strong><span>Every action is grounded in your current capability graph.</span></div>`; $('#approve-plan').disabled = Boolean(simulation.simulation.blocked.length); $('#approve-plan').textContent = behavior.status === 'deployed' ? 'Deployed' : 'Deploy behavior →'; $('#plan-dialog').showModal(); }
function page(name) { document.querySelectorAll('.page').forEach(item => item.classList.add('hidden')); $(`#${name}-page`).classList.remove('hidden'); document.querySelectorAll('.nav').forEach(item => item.classList.toggle('active', item.dataset.page === name)); }

$('#intent-form').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('#intent-input'); try { const behavior = await api('/behaviors', { method: 'POST', body: JSON.stringify({ intent: input.value }) }); input.value = ''; await refresh(); await review(behavior); } catch (error) { toast(error.message); } });
async function connectProvider(id) { try { const result = await api(`/connect/${id}`, { method: 'POST' }); if (result.authorizationUrl) { window.location.assign(result.authorizationUrl); return; } toast(`${providers.find(provider => provider.id === id)?.name || 'Provider'} connected. Syncing its capability graph…`); await api(`/sync/${id}`, { method: 'POST' }); await refresh(); } catch (error) { toast(error.message); } }
document.addEventListener('click', async (event) => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.intent) { $('#intent-input').value = button.dataset.intent; $('#intent-input').focus(); } if (button.dataset.page) page(button.dataset.page); if (button.classList.contains('connect-provider')) await connectProvider(button.dataset.provider); if (button.classList.contains('sync-provider')) { try { const result = await api(`/sync/${button.dataset.provider}`, { method: 'POST' }); toast(`Synchronized ${result.imported} device${result.imported === 1 ? '' : 's'}.`); await refresh(); } catch (error) { toast(error.message); } } if (button.classList.contains('revoke-agent')) { if (!confirm('Revoke this home agent? It will stop receiving behaviors.')) return; try { await api(`/agents/${button.dataset.agent}`, { method: 'DELETE' }); await refresh(); } catch (error) { toast(error.message); } } if (button.classList.contains('review')) { try { await review(behaviors.find(item => item.behaviorId === button.dataset.id)); } catch (error) { toast(error.message); } } });
$('#new-behavior').addEventListener('click', () => { page('home'); $('#intent-input').focus(); });
$('#approve-plan').addEventListener('click', async (event) => { event.preventDefault(); if (!candidate || candidate.status === 'deployed') return; try { await api(`/behaviors/${candidate.behaviorId}/deploy`, { method: 'POST' }); $('#plan-dialog').close(); toast('Behavior deployed. Nexus will evaluate matching environment events.'); await refresh(); } catch (error) { toast(error.message); } });
$('#stop-all').addEventListener('click', async () => { try { const result = await api('/emergency-stop', { method: 'POST' }); toast(`Emergency stop paused ${result.pausedBehaviors} deployed behavior${result.pausedBehaviors === 1 ? '' : 's'}.`); await refresh(); } catch (error) { toast(error.message); } });
$('#create-agent').addEventListener('click', async () => { const name = prompt('Name this home agent', 'My home'); if (!name) return; try { const agent = await api('/agents', { method: 'POST', body: JSON.stringify({ name }) }); $('#agent-token-command').textContent = `NEXUS_CLOUD_URL=${location.origin}\nNEXUS_CLOUD_AGENT_TOKEN=${agent.token}\nnpm run start:agent`; $('#agent-token-dialog').showModal(); await refresh(); } catch (error) { toast(error.message); } });
let registering = true;
$('#auth-mode').addEventListener('click', () => { registering = !registering; $('#name-field').classList.toggle('hidden', !registering); $('#auth-submit').textContent = registering ? 'Create account' : 'Sign in'; $('#auth-mode').textContent = registering ? 'Already have an account? Sign in' : 'Need an account? Create one'; });
$('#auth-form').addEventListener('submit', async event => { event.preventDefault(); $('#auth-error').textContent = ''; try { const result = await api(`/auth/${registering ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify({ email: $('#auth-email').value, password: $('#auth-password').value, displayName: $('#auth-name').value }) }); sessionToken = result.token; localStorage.setItem('nexus_session', sessionToken); account = result.user; $('#auth-dialog').close(); await boot(); } catch (error) { $('#auth-error').textContent = error.message; } });
$('#logout').addEventListener('click', () => { localStorage.removeItem('nexus_session'); sessionToken = null; location.reload(); });
async function boot() { if (!sessionToken) { $('#auth-dialog').showModal(); return; } try { account = await api('/auth/me'); const name = account.display_name || account.email?.split('@')[0] || 'Nexus user'; $('#profile-name').textContent = name; $('#profile-initials').textContent = name.slice(0, 2).toUpperCase(); $('#greeting').textContent = `Welcome, ${name}.`; await refresh(); } catch { localStorage.removeItem('nexus_session'); sessionToken = null; $('#auth-dialog').showModal(); } }
boot();
